config/routes.rb
Rails.application.routes.draw do
  resources :client_workouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'client_workouts/find' => 'client_workouts#find'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_workout.rb
class ClientWorkout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/client_workouts_controller.rb
class ClientWorkoutsController < ApplicationController
  before_action :set_client_workout, only: [:show, :edit, :update, :destroy]

  # GET /client_workouts
  # GET /client_workouts.json
  def index
    @client_workouts = ClientWorkout.all
  end

  # GET /client_workouts/1
  # GET /client_workouts/1.json
  def show
  end

  # GET /client_workouts/new
  def new
    @client_workout = ClientWorkout.new
  end

  # GET /client_workouts/1/edit
  def edit
  end

  # POST /client_workouts
  # POST /client_workouts.json
  def create
    @client_workout = ClientWorkout.new(client_workout_params)

    respond_to do |format|
      if @client_workout.save
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully created.' }
        format.json { render :show, status: :created, location: @client_workout }
      else
        format.html { render :new }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_workouts/1
  # PATCH/PUT /client_workouts/1.json
  def update
    respond_to do |format|
      if @client_workout.update(client_workout_params)
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_workout }
      else
        format.html { render :edit }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  def find
   #puts params[:search_string]
   # @results = ClientWorkout.where(client_name:params[:search_string])
   
   @results = ClientWorkout.where('lower(client_name) = ?', params[:search_string].downcase)
  
  end

  # DELETE /client_workouts/1
  # DELETE /client_workouts/1.json
  def destroy
    @client_workout.destroy
    respond_to do |format|
      format.html { redirect_to client_workouts_url, notice: 'Client workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_workout
      @client_workout = ClientWorkout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_workout_params
      params.require(:client_workout).permit(:client_name, :tainer, :duration_mins, :date_of_workout, :paid_amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_workouts_helper.rb
module ClientWorkoutsHelper
end

app/views/client_workouts/_form.html.erb
<%= form_with(model: client_workout, local: true) do |form| %>
  <% if client_workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_workout.errors.count, "error") %> prohibited this client_workout from being saved:</h2>

      <ul>
      <% client_workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name %>
  </div>

  <div class="field">
    <%= form.label :tainer %>
    <%= form.text_field :tainer %>
  </div>

  <div class="field">
    <%= form.label :duration_mins %>
    <%= form.number_field :duration_mins %>
  </div>

  <div class="field">
    <%= form.label :date_of_workout %>
    <%= form.date_select :date_of_workout %>
  </div>

  <div class="field">
    <%= form.label :paid_amount %>
    <%= form.text_field :paid_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/client_workouts/edit.html.erb
<h1>Editing Client Workout</h1>

<%= render 'form', client_workout: @client_workout %>

<%= link_to 'Show', @client_workout %> |
<%= link_to 'Back', client_workouts_path %>

app/views/client_workouts/find.html.erb
<p id="notice"><%= notice %></p>

<h1>Client Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Tainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |client_workout| %>
      <tr>
        <td><%= client_workout.client_name %></td>
        <td><%= client_workout.tainer %></td>
        <td><%= client_workout.duration_mins %></td>
        <td><%= client_workout.date_of_workout %></td>
        <td><%= client_workout.paid_amount %></td>
        <td><%= link_to 'Show', client_workout %></td>
        <td><%= link_to 'Edit', edit_client_workout_path(client_workout) %></td>
        <td><%= link_to 'Destroy', client_workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Workout', new_client_workout_path %>

app/views/client_workouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Client Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Tainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_workouts.each do |client_workout| %>
      <tr>
        <td><%= client_workout.client_name %></td>
        <td><%= client_workout.tainer %></td>
        <td><%= client_workout.duration_mins %></td>
        <td><%= client_workout.date_of_workout %></td>
        <td><%= client_workout.paid_amount %></td>
        <td><%= link_to 'Show', client_workout %></td>
        <td><%= link_to 'Edit', edit_client_workout_path(client_workout) %></td>
        <td><%= link_to 'Destroy', client_workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Workout', new_client_workout_path %>

app/views/client_workouts/new.html.erb
<h1>New Client Workout</h1>

<%= render 'form', client_workout: @client_workout %>

<%= link_to 'Back', client_workouts_path %>

app/views/client_workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @client_workout.client_name %>
</p>

<p>
  <strong>Tainer:</strong>
  <%= @client_workout.tainer %>
</p>

<p>
  <strong>Duration mins:</strong>
  <%= @client_workout.duration_mins %>
</p>

<p>
  <strong>Date of workout:</strong>
  <%= @client_workout.date_of_workout %>
</p>

<p>
  <strong>Paid amount:</strong>
  <%= @client_workout.paid_amount %>
</p>

<%= link_to 'Edit', edit_client_workout_path(@client_workout) %> |
<%= link_to 'Back', client_workouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <br/>
        <%= form_tag "/client_workouts/find" do %>
        <%= text_field_tag :search_string %>
        <%=submit_tag :search%>
        <%end%>
        <br/>
    <%= yield %>
  </body>
</html>